### ISSUE TITLE
Final Tasks [Meta-Issue]

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [switchonproject/cids-custom-switchon#155]
### "Meta-Issue" for [**Final Tasks**](https://github.com/switchonproject/cids-custom-switchon/milestone/2).
*Bugfixes, new Features and Ideas for improvements for the remainder of the project.*

- [x] [Add DOIs to existing datasets](https://github.com/switchonproject/cids-custom-switchon/issues/154) (cids-custom-switchon)
- [x] [Support adding DOIs for large files](https://github.com/switchonproject/cids-custom-switchon/issues/156) (cids-custom-switchon)
- [ ] [Improve SWITCH-ON meta-data sets](https://github.com/switchonproject/cids-custom-switchon/issues/157) (cids-custom-switchon)
- [ ] [Optimize Spatial Queries](https://github.com/switchonproject/cids-custom-switchon-server/issues/66) (cids-custom-switchon)
- [ ] [REST API Performance Optimisations](https://github.com/switchonproject/cids-custom-switchon-server/issues/67) (cids-custom-switchon-server)
- [ ] [Automatic Sitemap Generation](https://github.com/switchonproject/cids-custom-switchon-server/issues/68) (cids-custom-switchon-server)
- [x] [Show SWITCH-ON Resources](https://github.com/switchonproject/sip-html5/issues/139) (sip-html5)
- [x] [Search Engine Optimization](https://github.com/switchonproject/sip-html5/issues/140) (sip-html5)
- [ ] [Preview Datasets](https://github.com/switchonproject/sip-html5/issues/141) (sip-html5)
- [ ] [Performance Optimisations](https://github.com/switchonproject/sip-html5/issues/142) (sip-html5)
- [ ] [Identify SWITCH-ON Resource](https://github.com/switchonproject/sip-html5-resource-registration/issues/30) (cids-distribution-switchon)
- [x] [Improve User Feedback on Error](https://github.com/switchonproject/sip-html5-resource-registration/issues/31) (sip-html5-resource-registration)
- [ ] [Prepare new Release](https://github.com/switchonproject/cids-distribution-switchon/issues/2) (cids-distribution-switchon)
- [ ] [Upgrade Images to new Release](https://github.com/switchonproject/switchon-docker-images/issues/3) (switchon-docker-images)
- [ ] [Meta-Data Repository Image](https://github.com/switchonproject/switchon-docker-images/issues/4) (switchon-docker-images)
- [ ] [GeoServer and GeoWebCache Image](https://github.com/switchonproject/switchon-docker-images/issues/5) (switchon-docker-images)
- [ ] [Upgrade Volumes to new Release](https://github.com/switchonproject/switchon-docker-volumes/issues/3) (switchon-docker-volumes)
- [ ] [Meta-Data Repository Volume](https://github.com/switchonproject/switchon-docker-volumes/issues/4) (switchon-docker-volumes)
- [ ] [GeoServer and GeoWebCache Volume](https://github.com/switchonproject/switchon-docker-volumes/issues/5) (switchon-docker-volumes)
